server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/registration}
    username: ${SPRING_DATASOURCE_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:hello}
    password: ${SPRING_MAIL_PASSWORD:hello}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

